apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  password: {{ .Values.database.mysql.password | b64enc | quote }}
  root-password: {{ .Values.database.mysql.rootPassword | b64enc | quote }}