apiVersion: kustomize.toolkit.io/v1beta1
kind: Kustomization
metadata:
  name: myapp-production
  namespace: argocd
spec:
  path: argocd/apps/myapp/overlays/production
  prune: true
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: myapp-source
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: frontend
      namespace: default
    - apiVersion: apps/v1
      kind: Deployment
      name: backend
      namespace: default
